# (C) Copyright 2013
# Steve Shih <shihsung@gmail.com>
#
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= $(BOARD).o
